name: Build and push Chart

on:
  push:
    branches:
      - 'stable'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: stable

      - uses: azure/setup-helm@v4.2.0

      - name: Build Clickhouse chart
        run: helm package charts/clickhouse --version ${{ steps.semver.outputs.next }}
      - name: Build Sentry-Kubernetes chart
        run: helm package charts/sentry-kubernetes --version ${{ steps.semver.outputs.next }}
      - name: Build Sentry chart
        run: helm package charts/sentry -u --version ${{ steps.semver.outputs.next }}

      - name: Login into registry
        env:
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: printf "%s" "$REGISTRY_PASSWORD" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Sentry chart
        run: helm push sentry-${{ steps.semver.outputs.next }}.tgz oci://ghcr.io/kpn
